id: PBCAA99B9
initial_creation_type: input
source_metadata:
  title: 'BA: Daśabhūmikasūtra'
  language: zh
  volumes:
    e7445d7bfe0e4b8c9fcb8b6b2d5d3991:
      title: Complete text
      base_file: Complete text.txt
      work_id: W3F935563
  chapter_to_tile: {}
created_at: '2022-03-02T09:07:31.810149'
last_modified_at: '2022-03-02T09:07:31.810169'
